data_directory: /sc-projects/sc-proj-dh-ukb-intergenics/analysis/development/lesi11/testData
build_directory: /sc-projects/sc-proj-dh-ukb-intergenics/analysis/development/lesi11/build
results_directory: /sc-projects/sc-proj-dh-ukb-intergenics/analysis/development/lesi11/results


threads: 10

chromosomes: [1]

maf: 0.01
grm_cutoff: 0.025
covariates: False

