configfile: "/sc-projects/sc-proj-dh-ukb-intergenics/analysis/development/lesi11/code/GREML/workflow/config.yaml"
include: "rules/helpers.smk"
include: "rules/grm.smk"
include: "rules/dimension_reduction.smk"
include: "rules/phenotypes.smk"
include: "rules/greml.smk"
include: "rules/visualization.smk"

# ruleorder: merge_grm > chromosome_grm > grm_to_grm_gz


rule all:
    input:
        f"{config['results_directory']}/{config['dataset']['workname']}/conmpare_greml_summary.pdf",
        # f"{config['results_directory']}/{config['dataset']['workname']}/conmpare_greml_summary.tsv",
