# To use this profile, run snakemake with the following command: snakemake --profile profiles/snakemake_slurm
# This will not work for snakemake>=8.0.0, tested with snakemake=7.32.4

############ GENERAL ############
jobs: 10
latency-wait: 3000
local-cores: 1
use-conda: True
rerun-incomplete: True
show-failed-logs: True
keep-going: True

############ CLUSTER ############
jobscript: "jobscript.sh"
cluster: "sbatch --partition=compute \
    --time=24:00:00 \
    --mem={resources.mem_mb} \
    --cpus-per-task={threads} \
    --output=logs/{rule}/%j_{wildcards}.out \
    --error=logs/{rule}/%j_{wildcards}.err "
cluster-cancel: scancel

############ RESOURCES ############
default-resources:
    mem_mb: 4000
  
############ RULES ############
set-resources:
    filter_genome:
        mem_mb: 100000
    chromosome_grm:
        mem_mb: 100000
    merge_grm:
        mem_mb: 100000
    run_greml:
        mem_mb: 100000
    combine_datasets:
        mem_mb: 100000
    run_PCA:
        mem_mb: 100000
    run_kernelPCA:
        mem_mb: 100000
    grm_dim_reduction:
        mem_mb: 100000


set-threads:
    filter_genome: 56
    chromosome_grm: 56
    merge_grm: 56
    run_greml: 56
    combine_datasets: 56
    run_PCA: 56
    run_kernelPCA: 56
    grm_dim_reduction: 56
